[[autotasks]]
= Autotasks

_The Defender Autotasks service allows you to run small code snippets on a regular basis or via webhooks that can make calls to the Ethereum network or to external APIs. Thanks to tight integration to xref:relay.adoc[Relay], you can use Autotasks to automate regular actions on your contracts._

[[use-cases]]
== Use cases

Use Autotasks whenever you have a recurrent action you need to run on your Contracts. Since you can run arbitrary code snippets, you can trigger any transactions you need, checking whatever conditions you want, and gathering info from any external APIs you may need.

* Check your balance in contracts and *sweep funds to a wallet* upon reaching a threshold
* Update an *on-chain oracle* with information from an external API
* *Monitor your contracts* to verify their state or check that an off-chain data source is in-sync
* Poke your contracts to have them *transition to a new state* once a set of conditions is met
* Integrate with external *third party services* via webhooks
* Provide *gasless transactions* for your dapp users via meta-transactions

[[whats-in-an-autotask]]
== What's in an Autotask?

In a nutshell, an Autotask is a snippet of javascript code invoked at a regular interval, similar to a serverless function. And as a matter of fact, they are implemented with https://aws.amazon.com/lambda/[Lambda functions].

When you create an Autotask, you provide a javascript snippet, choose a trigger for it to run, and optionally <<relayer-integration,link it to a Relayer>>. Defender currently supports two types of triggers:

* *Schedule*: Choose a frequency to execute your Autotask, and Defender will make sure to invoke your function at the specified interval. Note that the specified interval is between two consecutive execution starts, _not_ between the end of an Autotask and the beginning of the next one.

* *Webhook*: Defender will create a secret URL for your Autotask, and invoke it whenever an HTTP request is POSTed to that endpoint. You can regenerate this URL at any time. Defender will inject the HTTP request information into your Autotask, and return the Autotask run info along with any data you return from your code.

NOTE: If you get a `{"message":"Missing Authentication Token"}` as the response to a Webhook HTTP request, double check that your request was actually a POST. You will typically see a `{"message":"Missing Authentication Token"}` response when issuing a GET.

Autotasks can also be manually executed from the UI for quick testing. The last 30 Autotask runs will be shown in the Autotask view, allowing you to access the run logs (generated via `console.log`) for troubleshooting. Additionally, when an Autotask fails, Defender will send you a notification email.

NOTE: Head over to the https://github.com/OpenZeppelin/defender-autotask-examples/[OpenZeppelin/defender-autotask-examples] repository for a quick start with an out-of-the-box Autotask example!

[[handler-function]]
=== Handler function

The code snippet must export a `handler` async function that will be invoked on each execution of the Autotask. Given that each Autotask is powered by an AWS Lambda behind the scenes, keep in mind that the same rules apply when https://docs.aws.amazon.com/lambda/latest/dg/runtimes-context.html[dealing with global variables].

[source,jsx]
----
exports.handler = async function() {
  // Your code here
}
----

[[relayer-integration]]
=== Relayer integration

If you connect your Autotask to a Relayer, then Defender will automatically inject temporary credentials to access your Relayer from your Autotask. Simply pass the event object to the relayer client in place of the credentials:

[source,jsx]
----
const { Relayer } = require('defender-relay-client');
 
exports.handler = async function(event) {
  const relayer = new Relayer(event);
  // Use relayer for sending txs or querying the network
}
----

This allows you to send transactions using your Relayer from your Autotasks without having to set up any API keys or secrets. Furthermore, you can also use the Relayer JSON RPC endpoint for making queries to any Ethereum network without having to configure API keys for external network providers.

[[webhook-handler]]
=== Webhook invocations

When your Autotask is invoked via a webhook, you can access the HTTP request info as part of the `event` parameter injected in your handler. Likewise, your return value will be included in the `result` field of the HTTP response payload.

[source,jsx]
----
exports.handler = async function(event) {
  const { 
    body,    // Object with JSON-parsed POST body
    headers, // Object with key-values from HTTP headers
    queryParameters, // Object with key-values from query parameters
  } = event.request;

  return {
    hello: 'world' // JSON-serialized and included in the `result` field of the response
  };
}
----

At the moment only JSON payloads are supported, and only non-standard headers with the `X-` prefix are provided to the Autotask. If any of these limitations is an issue for your use case, please mailto:defender@openzeppelin.com[reach out to us].

[[environment]]
=== Environment

Autotasks are executed in a https://nodejs.org/dist/latest-v12.x/docs/api/[node 12 runtime] with 256mb RAM and a 5-minute timeout. Code snippets are restricted to be smaller than 50mb in size. For ease-of-use, a set of common dependencies are pre-installed in the environment:

[source,jsx]
----
"defender-relay-client": "1.1.0",
"axios": "0.19.2",
"ethers": "5.0.3",
"web3": "1.2.9"
----

NOTE: If you need to use any dependency not listed above, you can either use a javascript module bundler such as rollup or webpack to include it in your code or just contact us to add it to the set of common dependencies. Refer to https://github.com/OpenZeppelin/defender-autotask-examples/tree/master/rollup[this sample project] for more info.

[[local-development]]
=== Local development

To reproduce exactly the same Autotask environment in your development setup, you can use the following lockfile to install the same set of dependencies via `yarn install --frozen-lockfile`.

📎 link:{attachmentsdir}/yarn.lock[yarn.lock]

You can also use the following template for local development, which will run your Autotask code when invoked locally using `node`. It will load the Relayer credentials from environment variables when run locally, or use the injected credentials when run in Defender.

[source,jsx]
----
const { Relayer } = require('defender-relay-client');

// Entrypoint for the Autotask
exports.handler = async function(credentials) {
  const relayer = new Relayer(credentials);
  // Use relayer for sending txs
}

// To run locally (this code will not be executed in Autotasks)
if (require.main === module) {
  const { API_KEY: apiKey, API_SECRET: apiSecret } = process.env;
  exports.handler({ apiKey, apiSecret })
    .then(() => process.exit(0))
    .catch(error => { console.error(error); process.exit(1); });
}
----

[[a-complete-example]]
== A complete example

The following example uses ethers.js and the Autotask Relayer integration to send a transaction calling `execute` on a given contract, prior checking a `canExecute` view function. Note that you would need to replace `ADDRESS` and `ABI` in the following code by their corresponding values.

[source,jsx]
----
const { ethers } = require("ethers");
const { DefenderRelaySigner, DefenderRelayProvider } = require('defender-relay-client/lib/ethers');

// Entrypoint for the Autotask
exports.handler = async function(credentials) {
  // Initialize defender relayer provider and signer
  const provider = new DefenderRelayProvider(credentials);
  const signer = new DefenderRelaySigner(credentials, provider, { speed: 'fast' });

  // Create contract instance from the signer and use it to send a tx
  const contract = new ethers.Contract(ADDRESS, ABI, signer);
  if (await contract.canExecute()) {
    await contract.execute();
  }
  console.log(`Called execute at ${ADDRESS}`);
}

// To run locally (this code will not be executed in Autotasks)
if (require.main === module) {
  const { API_KEY: apiKey, API_SECRET: apiSecret } = process.env;
  exports.handler({ apiKey, apiSecret })
    .then(() => process.exit(0))
    .catch(error => { console.error(error); process.exit(1); });
}
----

NOTE: Note that we are not waiting for the transaction to be mined. The Defender Relayer will take care of monitoring the transaction and resubmitting if needed. The Autotask should just send the request to the Relayer and exit.

[[security-considerations]]
== Security considerations

Each Autotask is implemented as a separate AWS Lambda, ensuring strong separation among each individual Autotask and across Defender tenants.

Autotasks are restricted via Identity and Access Management to have zero access to the Defender internal infrastructure. The only exception is that an Autotask may access its linked Relayer, which is negotiated via temporary credentials injected by the Defender Autotask service upon each execution. Still, the Autotask can only call the Relayer exposed methods and has no direct access to the backing private key.

[[coming-up]]
== Coming up...

We want to simplify uploading code to an Autotask, so we are experimenting with console-based approaches that can be called from a development environment or hooked into a CD pipeline to ensure your Autotasks are always up to date. Let us know if you have anything in mind!
