= Defender

OpenZeppelin Defender provides a security operations (SecOps) platform for Ethereum with built-in best practices. Development teams implement Defender to ship faster and minimize security risks.

[[get-started]]
== Get started

Signing up to Defender is free! Just head over to https://hubs.li/H0F1_Q50[defender.openzeppelin.com], hit Sign In, and choose to create a new account. After verifying your email address, you will be redirected to your own Defender account. See below for how to invite more users to your team!

[.card-section.card-section-2col]
== Components

Automate your Ethereum operations to deliver high-quality products faster with lower risk to users. Learn more about each component by clicking on its card.

[.card.card-learn]
--
xref:admin.adoc[[.card-title]#Admin# [.card-body]#pass:q[Automate and secure all your smart contract administration.]#]
--

[.card.card-learn]
--
xref:relay.adoc[[.card-title]#Relay# [.card-body]#pass:q[Build with private and secure transaction infrastructure.]#]
--

[.card.card-learn]
--
xref:sentinel.adoc[[.card-title]#Sentinel# [.card-body]#pass:q[Monitor smart contracts and send notifications.]#]
--

[.card.card-learn]
--
xref:autotasks.adoc[[.card-title]#Autotask# [.card-body]#pass:q[Create automated scripts to call your smart contracts.]#]
--

[.card.card-learn]
--
xref:advisor.adoc[[.card-title]#Advisor# [.card-body]#pass:q[Learn and implement security best practices.]#]
--

[[networks]]
== Available networks

All Defender components, where applicable, provide support for the Ethereum *Mainnet*, as well as the *Rinkeby*, *Ropsten*, *Kovan*, and *Goerli* test networks, plus the https://www.xdaichain.com/[*xDai*], https://fuse.io/[*Fuse*], https://docs.binance.org/smart-chain/guides/bsc-intro.html[*Binance Smart Chain*], https://fantom.foundation/what-is-fantom-opera/[*Fantom*], https://docs.moonbeam.network/networks/testnet/[*Moonbase*], https://docs.matic.network/docs/develop/network-details/network[*Polygon* (Matic)], https://docs.avax.network/learn/platform-overview#contract-chain-c-chain[Avalanche C], https://celo.org/[Celo] and https://arbitrum.io/[Arbitrum] chains, along with their respective testnets where applicable. 

If there is any other network or layer-2 solution you would like to use from Defender, please <<feedback,reach out to us>>!

[[tiers]]
== Usage quotas and support

Right after signing up to Defender for free you get access to all Defender features with the usage limits specified below:

- 20 Team collaborators.
- 30 Admin contracts.
- 5 relayers.
- 120 relayer transactions per hour.
- 20 autotasks.
- 120 autotask runs per hour, with a minimum frequency of 1 minute per autotask. 
- 20 sentinels.
- 10,000 JSON RPC queries per hour (consumed by Admin and Relayer).

In addition, you can reach out to our https://forum.openzeppelin.com/c/support/defender/36[Community Forum] for help using Defender.

=== Increasing quotas and accessing direct support

If you are interested in increasing any of the default quota limits and getting direct support from us through email, Slack or Telegram, https://heregoestheform.link[please fill in this form] and a member of OpenZeppelin will get in contact with you shortly after.

[[feedback]]
== Feedback

As a Defender user, your feedback is important! We are committed to making Defender a product that will help you in the secure management of your project, and we cannot do that without your input. Feel free to reach out with questions, feature requests, or issues, via the https://forum.openzeppelin.com/c/support/defender/36[Community Forum].
