= Defender

_Welcome to the OpenZeppelin Defender documentation! Here you'll find all the info you need about Defender._

[.card-section-2col]
[[components]]
== Components

[.card.card-learn]
--
xref:admin.adoc[[.card-title]#Admin# [.card-body]#pass:q[Seamlessly manage your smart contract administration including access controls, multi-sig, upgrades, and whitelisting.]#]
--

[.card.card-learn]
--
xref:relay.adoc[[.card-title]#Relay# [.card-body]#pass:q[Quickly implement private relayers with support for testnets, mainnet, layer 2 and sidechains. Increase user security with embedded key vaults, API key management, and meta-transactions.]#]
--

[.card.card-learn]
--
xref:autotasks.adoc[[.card-title]#Autotasks# [.card-body]#pass:q[Easily create and run scripts in a serverless environment that call your smart contracts and other web services, automating your operations and lowering attack risk.]#]
--

[.card.card-learn]
--
xref:advisor.adoc[[.card-title]#Advisor# [.card-body]#pass:q[Stay up to date with the latest security best practices. Use step-by-step guides to implement them across development, testing, monitoring and operations.]#]
--

[[shared-access]]
== Shared access

Access to all resources in Defender is shared across all users in your organization. This means that every Relayer or Autotask you have created will also be accessible by any of your team members — there is no concept of user-based ownership.

[[user-management]]
== User management

You can review your team members under the Collaborators section, accessible from the top-right user menu. You can also invite new users to your team from there.

[[feedback]]
== Feedback

We are super interested in your feedback! We are committed to making Defender a product that will help you in the secure management of your project, and we cannot do that without your thoughts. Feel free to shoot us a line whenever anything comes to mind, either via the https://forum.openzeppelin.com/c/support/defender/36[Community Forum], Telegram, or at contact@openzeppelin.com.
