= Defender

OpenZeppelin Defender is a platform to automate Ethereum operations. Here you’ll find all the info you need about Defender, including specifics on the four main features: 

Admin: automated smart contract administration
Relay: secure, private relayers with gas optimization
Autotasks: serverless functions to securely call smart contracts
Advisor: actionable security best practices 

If you need an account, you can https://openzeppelin.com/defender/[sign up for free]. 


[.card-section-2col]
[[components]]
== Components

[.card.card-learn]
--
xref:admin.adoc[[.card-title]#Admin# [.card-body]#pass:q[Seamlessly manage your smart contract administration including access controls, multi-sig, upgrades, and whitelisting.]#]
--

[.card.card-learn]
--
xref:relay.adoc[[.card-title]#Relay# [.card-body]#pass:q[Quickly implement private relayers with support for testnets, mainnet, layer 2 and sidechains. Increase user security with embedded key vaults, API key management, and meta-transactions.]#]
--

[.card.card-learn]
--
xref:autotasks.adoc[[.card-title]#Autotasks# [.card-body]#pass:q[Easily create and run scripts in a serverless environment that call your smart contracts and other web services, automating your operations and lowering attack risk.]#]
--

[.card.card-learn]
--
xref:advisor.adoc[[.card-title]#Advisor# [.card-body]#pass:q[Stay up to date with the latest security best practices. Use step-by-step guides to implement them across development, testing, monitoring and operations.]#]
--

[[sign-up]]
== Signing up

Signing up to Defender is free! Just head over to https://defender.openzeppelin.com/[defender.openzeppelin.com], hit Sign In, and choose to create a new account. After verifying your email address, you will be redirected to your own Defender account on the free plan. See below for how to invite more users to your team!

[[user-management]]
== User management and shared access

Access to all resources in Defender is shared across all users in your team. This means that every Relayer or Autotask you have created will also be accessible by any of your team members — there is no concept of user-based ownership.

You can review your team members under the Collaborators section, accessible from the top-right user menu. You can also invite new users to your team from there. A user can only belong to a single team in Defender (for now).

WARNING: If you want to add a user to your team, make sure to invite them from the Collaborators section. If they sign up directly to the application, they will be added to a new team of their own instead. If this happens, contact us at mailto:defender@openzeppelin.com[defender@openzeppelin.com] and we'll help.

[[tiers]]
=== Tiers and quotas

The Defender free plan is restricted for testnet access only. In addition, you may only create up to five Relayers and Autotasks, import up to five Contracts into Admin, and have up to five Users in your team. The total number of transactions sent from Relayers cannot exceed 30 per hour, and the same limit applies for Autotask runs.

If you want access to mainnet or to increase any of the quota limits from the free plan, please apply via https://openzeppelin.com/apply/[this form] and we'll reach out to you.

[[feedback]]
== Feedback

We are super interested in your feedback! We are committed to making Defender a product that will help you in the secure management of your project, and we cannot do that without your thoughts. Feel free to shoot us a line whenever anything comes to mind, either via the https://forum.openzeppelin.com/c/support/defender/36[Community Forum], Telegram, or at mailto:defender@openzeppelin.com[defender@openzeppelin.com].
