[[defender-docs]]
= Defender Docs

_Welcome to the OpenZeppelin Defender documentation! Here you'll find all the info you need about Defender._

[[components]]
== Components

xref:admin.adoc[Admin]

xref:relay.adoc[Relay]

xref:autotasks.adoc[Autotasks]

xref:advisor.adoc[Advisor]

[[shared-access]]
== Shared access

Access to all resources in Defender is shared across all users in your organization. This means that every Relayer or Autotask you have created will also be accessible by any of your team members — there is no concept of user-based ownership.

[[user-management]]
== User management

You can review your team members under the Collaborators section, accessible from the top-right user menu. You can also invite new users to your team from there.

== Two factor authentication (2FA)

We strongly suggest that you enable 2FA to improve your Defender account security. As a second authentication factor, Defender relies on the https://en.wikipedia.org/wiki/Time-based_One-time_Password_algorithm[Time-based One-Time Password standard (TOTP)]. To enable 2FA on Defender, you need a TOTP compliant application, such as https://authy.com/[Authy] or Google Authenticator. You can enable 2FA under the Account settings section, accessible from the top-right user menu. Defender will guide you through the necessary steps.


[[feedback]]
== Feedback

We are super interested in your feedback! We are committed to making Defender a product that will help you in the secure management of your project, and we cannot do that without your thoughts. Feel free to shoot us a line whenever anything comes to mind, either via the https://forum.openzeppelin.com/c/support/defender/36[Community Forum], Telegram, or at contact@openzeppelin.com.
