= Defender

OpenZeppelin Defender provides a security operations (SecOps) platform for Ethereum with built-in best practices. Development teams implement Defender to ship faster and minimize security risks.

[[get-started]]
== Get started

Signing up to Defender is free! Just head over to https://hubs.li/H0F1_Q50[defender.openzeppelin.com], hit Sign In, and choose to create a new account. After verifying your email address, you will be redirected to your own Defender account on the free plan. See below for how to invite more users to your team!

[.card-section.card-section-2col]
== Components

Automate your Ethereum operations to deliver high-quality products faster with lower risk to users. Learn more about each component by clicking on its card.

[.card.card-learn]
--
xref:admin.adoc[[.card-title]#Admin# [.card-body]#pass:q[Automate and secure all your smart contract administration.]#]
--

[.card.card-learn]
--
xref:relay.adoc[[.card-title]#Relay# [.card-body]#pass:q[Build with private and secure transaction infrastructure.]#]
--

[.card.card-learn]
--
xref:sentinel.adoc[[.card-title]#Sentinel# [.card-body]#pass:q[Monitor smart contracts and send notifications.]#]
--

[.card.card-learn]
--
xref:autotasks.adoc[[.card-title]#Autotask# [.card-body]#pass:q[Create automated scripts to call your smart contracts.]#]
--

[.card.card-learn]
--
xref:advisor.adoc[[.card-title]#Advisor# [.card-body]#pass:q[Learn and implement security best practices.]#]
--

[[networks]]
== Available networks

All Defender components, where applicable, provide support for the Ethereum *Mainnet*, as well as the *Rinkeby*, *Ropsten*, *Kovan*, and *Goerli* test networks, plus the https://www.xdaichain.com/[*xDai*], https://fuse.io/[*Fuse*], https://docs.binance.org/smart-chain/guides/bsc-intro.html[*Binance Smart Chain*], https://fantom.foundation/what-is-fantom-opera/[*Fantom*], https://docs.moonbeam.network/networks/testnet/[*Moonbase*], https://docs.matic.network/docs/develop/network-details/network[*Polygon* (Matic)], and https://docs.avax.network/learn/platform-overview#contract-chain-c-chain[Avalanche C] chains, along with their respective testnets where applicable. Note that some networks may be unavailable depending on your <<tiers,plan>>.

If there is any other network or layer-2 solution you would like to use from Defender, please <<feedback,reach out to us>>!

[[tiers]]
== Plans and quotas

The Defender free plan is restricted for testnet access only. In addition, you may only create up to five Relayers and Autotasks, import up to five Contracts into Admin, and have up to five Users in your team. The total number of transactions sent from Relayers cannot exceed 30 per hour, and the same limit applies for Autotask runs.

If you want access to Mainnet, xDai, BSC, Fantom, Fuse, Matic, or Avalanche, or to increase any of the quota limits from the free plan, you can upgrade your plan to Team or Individual in the Account Plan menu in the top-right menu in Defender.

[[feedback]]
== Feedback

As a Defender user, your feedback is important! We are committed to making Defender a product that will help you in the secure management of your project, and we cannot do that without your input. Feel free to reach out with questions, feature requests, or issues, either via the https://forum.openzeppelin.com/c/support/defender/36[Community Forum], Telegram, or at mailto:defender@openzeppelin.com[defender@openzeppelin.com].
