[[relay]]
= Relay

_The Defender Relay service allows you to send transactions via a regular HTTP API, and takes care of private key secure storage, transaction signing, nonce management, gas price estimation, and resubmissions. This way you don't need to worry about securing your private keys in your backend scripts, or by monitoring your transactions to ensure they get mined._

[[use-cases]]
== Use cases

Use a Defender Relayer every time you find yourself using a hot wallet in your code. Whenever you need to send a transaction from a script or your backend, you can connect to a Relayer instead to simplify key management and transaction submissions.

* *Poking your contracts* to trigger a state transition
* Update an *on-chain oracle* with external data
* Sending *meta-transactions* to build a gasless experience
* React to sign-ups in your app by *airdropping tokens* to your new users
* *Sweeping funds* from protocol contracts to secure wallets
* *Building bots* for interacting with smart contract protocols

[[whats-in-a-relayer]]
== What's in a Relayer?

Each Defender Relayer is an Ethereum account assigned exclusively to your team. Every time you create a new Relayer, Defender will create a new private key in a secure vault. Whenever you request Defender to send a transaction through that Relayer, the corresponding private key will be used for signing.

You can think of each Relayer as a queue for sending transactions, where all transactions sent through the same Relayer will be sent in order and from the same Ethereum account, controlled exclusively by your team. Skip ahead to the <<under-the-hood,Under the hood>> section if you want more info on how Relayers work behind the scenes!

IMPORTANT: Relayers on the _Goerli_ and _Rinkeby_ networks will be **automatically funded** with test ETH upon creation, and will be topped up when they run low on funds. On other networks, you'll need to fund each Relayer individually with ETH to ensure they have enough funds to pay for the gas of the transactions you send. In these cases, Defender will send you an email notification if a Relayer's funds drop below 0.1 ETH.

NOTE: Defender Relayers are implemented as Externally Owned Accounts. We are working to implement Smart Accounts in the future as well, to support batched transactions, gas tokens, and cold keys for on-chain management.

[[api-keys]]
=== API Keys

Each Relayer has one or more *API keys* associated with it. In order to send a transaction through a Relayer, you will need to authenticate the request with one an API key/secret pair. You can create or delete API keys as you see fit, and this will not change the sending address or Relayer balance.

WARNING: When creating a new API key, keep in mind that the API secret is only visible once during the creation — if you don't write it down, it's lost forever. Luckily, creating a new API key is as easy as clicking a button.

[[sending-transactions]]
== Sending transactions

The easiest way to send a transaction via a Relayer is using the https://www.npmjs.com/package/defender-relay-client[`defender-relay-client`] npm package. The client is initialized with an API key/secret and exposes a simple API for sending transactions through the corresponding Relayer.

[source,jsx]
----
import { Relayer } from 'defender-relay-client';
const relayer = new Relayer({apiKey: YOUR_API_KEY, apiSecret: YOUR_API_SECRET});

const tx = await relayer.sendTransaction({
  to, value, data, gasLimit, speed: 'fast'
});
----

NOTE: You don't need to enter a private key when initializing a Relayer client, since the private key is kept secure in the Defender vault.

[[using-ethers.js]]
=== Using ethers.js

To avoid rewriting existing scripts, the Relayer client also integrates with https://docs.ethers.io/v5/[ethers.js] via a custom https://docs.ethers.io/v5/api/signer/[signer]. This allows you to switch to Defender Relayer for sending transactions with minimal changes in your codebase.

[source,jsx]
----
const { DefenderRelaySigner } = require('defender-relay-client/lib/ethers');
const { ethers } = require('ethers');
 
const provider = ethers.getDefaultProvider(NETWORK);
const credentials = { apiKey: YOUR_API_KEY, apiSecret: YOUR_API_SECRET };
const signer = new DefenderRelaySigner(credentials, provider, 
  { from: YOUR_RELAYER_ADDRESS, speed: 'fast' }
);

const erc20 = new ethers.Contract(ERC20_ADDRESS, ERC20_ABI, signer);
const tx = await erc20.functions.transfer(beneficiary, 1e18.toString());
const mined = await tx.wait();
----

NOTE: Due to a limitation, you will need to provide not just the API key/secret but also the Relayer Ethereum address when initializing the `DefenderRelaySigner` object. We are working to remove this requirement.

[[speed]]
=== Speed

Instead of the usual `gasPrice`, the Relayer accepts a https://www.npmjs.com/package/defender-relay-client#speed[`speed`] parameter, which can be `safeLow`, `average`, `fast`, or `fastest`. These values are mapped to actual gas prices when the transaction is sent or resubmitted and vary depending on the state of the network.

NOTE: Today, mainnet gas prices for each speed are obtained from https://ethgasstation.info/[ethgasstation], falling back to https://etherchain.org/tools/gasPriceOracle[etherchain] if the former is not available. We are experimenting with other gas price oracles in the meantime. Testnet gas prices are obtained from a call to `eth_gasPrice` to the network.

[[transaction-ids]]
=== Transaction IDs

Since the Relayer may resubmit a transaction with an updated gas price if it does not get mined in the expected timeframe, the `hash` of a given transaction may change over time. To track the status of a given transaction, the Relayer API returns a `transactionId` identifier you can use to https://www.npmjs.com/package/defender-relay-client#querying[query] it.

[source,jsx]
----
const latestTx = await relayer.query(tx.transactionId);
----

NOTE: The `query` endpoint will return the latest view of the transaction from the Defender service, which gets updated every few minutes.

[[signing]]
=== Signing

In addition to sending transactions, the Relayer can also sign arbitrary messages using its private key. You can access this feature via the `sign` method of the client or the equivalent ethers.js method.

[source,jsx]
----
const signResponse = await relayer.sign({ message });
----

[[autotasks-integration]]
=== Autotasks integration

A Relayer can be attached to an xref:autotask.adoc[Autotask]. When doing so, the Autotask code will have direct access to the attached Relayer methods _without requiring you to specify an API key_. Instead, Defender will inject short-lived credentials for your Relayer in your Autotask `handler` function.

[source,jsx]
----
const { Relayer } = require('defender-relay-client');

// The credentials object is injected by the Defender Autotasks engine 
exports.handler = async function(credentials) {
  const relayer = new Relayer(credentials);
  // ... use relayer as usual
}
----

[[pausing]]
=== Pausing

You can pause a Relayer from the Defender website, to quickly respond to an emergency. This will cause the Relayer to reject any incoming requests to send a transaction, whether it is from an Autotask or via the API. However, keep in mind that any transactions already sent will not be cancelled. When you are ready to resume operations, just hit the Unpause button and your Relayer will go back to normal.

[[meta-transactions]]
=== Meta-transactions

Defender Relayers are general-purpose relayers, in the sense that you can use them to send any transaction you want to your contracts. In particular, they can also be used for relaying meta-transactions on behalf of your users. A simple setup for this requires setting up a server-side function that decides whether or not to relay a given meta-transaction, and then calls the Defender Relayer for effectively sending it.

NOTE: If you would like to use Autotasks to host the server-side function to decide whether to pay for a meta-transaction request, let us know! We are working on a webhooks integration that can be used for this purpose.

[[eip2771-gsnv2-compatible-meta-transactions]]
==== EIP2771 GSNv2-compatible meta-transactions

We have created a demo application for Defender-powered meta-txs https://defender-example-metatx-relay.netlify.app/[here]. This application relies on an https://eips.ethereum.org/EIPS/eip-2771[EIP-2771 `Forwarder` contract]. This contract's sole responsibility is to receive a signed meta-tx request, verify its signature, and forward the request to a recipient contract by appending the signer address to the call.

This setup is compatible with https://docs.opengsn.org/[GSNv2], meaning that you can use a Defender Relayer for sending your meta-transactions, and at any point in the future, you can switch to the decentralized network of GSN relayers _without any changes to your contracts._

NOTE: You can explore the key parts of the code for the application https://gist.github.com/spalladino/7fb3533e36e9b9a833f8e5c568c86815[here].

[[more-meta-transaction-patterns]]
==== More meta-transaction patterns

The pattern described above is just one variant among several meta-transaction flavors available. Given that Defender Relayers are general-purpose, you can also use them for any other type of meta-transactions, such as relaying gasless ERC20 transfers using https://eips.ethereum.org/EIPS/eip-2612[EIP2612] or https://eips.ethereum.org/EIPS/eip-3009[EIP3009].

NOTE: We are also working on adding support for sidechains and L2s, starting with xDai. This way, you can offer a full gasless experience to your users in other networks. Let us know if you have any preferred network you'd like to see in Defender!

[[under-the-hood]]
== Under the hood

Each Relayer is associated to a private key. When a request to send a transaction is received, the Relayer validates the request, atomically assigns it a nonce, reserves balance for paying for its gas fees, resolves its speed to a gas price, signs it with its private key, and enqueues it for submission to the blockchain. The response is sent back to the client only after this process has finished. Then, the transaction is broadcasted through both Infura and Alchemy for redundancy and retried up to three times in case both APIs are down.

Every five minutes, all in-flight transactions are checked by the system. If they have not been mined and more than a certain time has passed (which depends on the transaction speed), they are resubmitted with a 10% increase in their gas price (or the latest gas price for their speed, if it's greater), which could be up to a *150% of the reported gas price for their speed*. This process causes the transaction hash to change, but their ID is preserved. On the other hand, if the transaction has been mined, it is still monitored for several blocks until we consider it to be confirmed.

[[security-considerations]]
== Security considerations

All private keys are stored in the AWS Key Management Service. Keys are generated within the KMS and never leave it, i.e., all sign operations are executed within the KMS. Furthermore, we rely on dynamically generated AWS Identity and Access Management policies to isolate access to the private keys among tenants.

As for API secrets, these are only kept in memory during creation when they are sent to the client. After that, they are hashed and stored securely in AWS Cognito, which is used behind the scenes for authenticating Relayer requests. This makes API keys easy to rotate while preserving the same private key on the KMS.

[[relay-api]]
== Relay API
The Relay API exposes two endpoints `txs` and `sign`. The `txs` endpoint allows to send transactions to Ethereum blockchain and query their status. The `sign` endpoint allows to sign arbitrary data with relayer's private key.

=== Getting JWT Token
JWT Token is requred to make requests to Relay API. For security reasons authentication uses https://en.wikipedia.org/wiki/Secure_Remote_Password_protocol[SRP protocol] and it is not possbile to retrive a JWT Token via one HTTP request. What is why it is advised to use https://docs.aws.amazon.com/cognito/latest/developerguide/cognito-integrate-apps.html[Amazon Cognito User Pool SDK] to retreive a JWT token.

Here is an example of getting a JWT Token in nodejs using `amazon-cognito-identity-js`. The Username/Password pair is your ApiKey/ApiSecret pair. PoolId and PoolClientId are always the same.

```JavaScript
import { AuthenticationDetails, CognitoUserPool, CognitoUser } from 'amazon-cognito-identity-js';

// eslint-disable-next-line @typescript-eslint/no-var-requires
global.fetch = require('node-fetch').default;

export const RelayerPoolId = () => process.env.RELAY_POOL_ID || 'us-west-2_iLmIggsiy'; // always the same
export const RelayerPoolClientId = () => process.env.RELAY_POOL_CLIENT_ID || '1bpd19lcr33qvg5cr3oi79rdap'; // always the same

type UserPass = { Username: string; Password: string };

export async function authenticate(authenticationData: UserPass): Promise<string> {
  const authenticationDetails = new AuthenticationDetails(authenticationData);
  const poolData = {
    UserPoolId: RelayerPoolId(),
    ClientId: RelayerPoolClientId(),
  };

  const userPool = new CognitoUserPool(poolData);
  const userData = { Username: authenticationData.Username, Pool: userPool };
  const cognitoUser = new CognitoUser(userData);

  return new Promise((resolve, reject) => {
    cognitoUser.authenticateUser(authenticationDetails, {
      onSuccess: function (session) {
        const token = session.getAccessToken().getJwtToken();
        resolve(token);
      },
      onFailure: function (err) {
        console.error(`Failed to get a token for the API key ${authenticationData.Username}`, err);
        reject(err);
      },
    });
  });
}
```

For a python users it is possible to retrive a JWT token using https://github.com/capless/warrant#cognito-srp-utility[warrant] library.

Here is an example:
```python
import boto3
from warrant.aws_srp import AWSSRP

client = boto3.client('cognito-idp')
aws = AWSSRP(username='API_KEY', password='API_SECRET', pool_id='us-west-2_iLmIggsiy', client_id='1bpd19lcr33qvg5cr3oi79rdap', client=client)
tokens = aws.authenticate_user()
print('Access Token', tokens['AuthenticationResult']['AccessToken'])
```

=== Making Requests

Once you get a JWT Token you can make requests to Defender API. A request requires ApiKey, JWT Token, optionally a payload, and API URL. Set $KEY, $TOKEN to the values of API Key and JWT Token accuired before. $END_POINT can be either `txs` or `sign`.

```bash
API_URL='http://api.defender.openzeppelin.com/'

curl \
  -H 'Accept: application/json' \
  -H 'Content-Type: application/json' \
  -H "X-Api-Key: $KEY" \
  -H "Authorization: Bearer $TOKEN" \
    "$API_URL/$END_POINT"
```

=== Txs Endpoint

==== Send Transaction
To send a transaction to Ethereum blockchain submit a POST request with a desired payload. Payload format:

```TypeScript
export type Address = string;
export type BigUInt = string | number;
export type Hex = string;
export type Speed = 'safeLow' | 'average' | 'fast' | 'fastest';

export interface SendTransactionRequest {
  to: Address;
  value?: BigUInt; // optional
  data?: Hex; // optional 
  speed?: Speed; // optional
  gasLimit: BigUInt;
}
```
An example of the request:

```bash
DATA='{ "to": "0x179810822f56b0e79469189741a3fa5f2f9a7631", "value": "1", "speed": "fast", "gasLimit": "21000" }'

curl \
  -X POST \
  -H 'Accept: application/json' \
  -H 'Content-Type: application/json' \
  -H "X-Api-Key: $KEY" \
  -H "Authorization: Bearer $TOKEN" \
  -d "$DATA" \
    "$API_URL/txs"
```

You would receive a response in the following format:

```TypeScript
export type Address = string;
export type BigUInt = string | number;
export type Hex = string;
export type Speed = 'safeLow' | 'average' | 'fast' | 'fastest';
export type Status = 'pending' | 'sent' | 'submitted' | 'inmempool' | 'mined' | 'confirmed';

export interface TransactionResponse {
  transactionId: string; // Defender tx id
  hash: string; // Ethereum hash
  to: Address;
  from: Address;
  value: string;
  data: string;
  speed: Speed;
  gasPrice: number;
  gasLimit: number;
  nonce: number;
  status: Status;
  chainId: number;
}
```
==== Query Transaction
To retrive a transaction status and data make a GET request to the `txs` endpoint with the Defender transaction id.

An example of the request:

```bash

curl \
  -X GET \
  -H 'Accept: application/json' \
  -H 'Content-Type: application/json' \
  -H "X-Api-Key: $KEY" \
  -H "Authorization: Bearer $TOKEN" \
    "$API_URL/txs/$ID"

```

You would receive a `TransactionResponse` object, e.g.:

```JSON
{
   "chainId":4,
   "hash":"0xcef95469a9f02757f0968ec8c11449ae5e7486073075381dcd62bacec9e5d627",
   "transactionId":"affba150-e563-441e-ae49-04bd6050979a",
   "value":"0x1",
   "gasPrice":1000000000,
   "gasLimit":21000,
   "to":"0x179810822f56b0e79469189741a3fa5f2f9a7631",
   "from":"0xbce0b5b71668e42d908e387b68dba91789c932b8",
   "data":"0x",
   "nonce":160,
   "status":"mined",
   "speed":"fast"
}
```

=== Sign Endpoint
To sign an arbitrary data with Relay API make a POST request with a payload contain a hex string. Payload format:

```TypeScript
export interface SignMessagePayload {
  message: Hex;
}
```

An example of the request:

```bash
DATA='{ "message": "0x0123456789abcdef" }'

curl \
  -X POST \
  -H 'Accept: application/json' \
  -H 'Content-Type: application/json' \
  -H "X-Api-Key: $KEY" \
  -H "Authorization: Bearer $TOKEN" \
  -d "$DATA" \
    "$API_URL/sign"
```
You would receive a response in the following format:

```TypeScript
export interface SignedMessagePayload {
  sig: Hex;
  r: Hex;
  s: Hex;
  v: number;
}
```

An example of the response:

```JSON
{
   "r":"0x819b2645a0b73494724dac355e6ecfc983d94597b533d34fe3ecd0277046a1eb",
   "s":"0x3b73c695b47dd275d17246d86bbfe35f112a7bdb5bf4a5a1a8e22fe37dfd005a",
   "v":44,
   "sig":"0x819b2645a0b73494724dac355e6ecfc983d94597b533d34fe3ecd0277046a1eb3b73c695b47dd275d17246d86bbfe35f112a7bdb5bf4a5a1a8e22fe37dfd005a2c"
}
```

=== Refreshing JWT Token
JWT token will expire in 60 minutes. If you code requires session longer than 60 minutes consider recreating a JWT token or using refresh token.

An example of how it can be done in nodejs:

```Javascript
async wrapApiCall(fn) {
  try {
    return await fn();
  } catch (error) {
    // this means ID token has expired so we'll recreate JWT token and try again.
    if (error.response.status === 401 && error.response.statusText === 'Unauthorized') {
      // getToken will retrive a fresh JWT token.
      await getToken();
      return await fn();
    }
    throw error;
  }
}
```
Where `fn` is a function making an API call.

[[coming-up]]
== Coming up...

We are working on new features, such as automatic top-ups of testnet Relayers, xDai support, and Relayer policies to restrict maximum expenditure. Stay tuned, and let us know if you have any requests!
