[[remix-plugin]]
= Remix Plugin

When coding and compiling contracts from https://remix.ethereum.org/[Remix IDE, window=_blank], you can use Defender Plugin to deploy your contracts by configuring a xref:module/deploy.adoc[Deployment Environment] and using an Approval Process as deployer.

[[installation]]
== Installation

1. Go to https://remix.ethereum.org/[Remix IDE, window=_blank] and click on Plugin manager (bottom left corner).
2. Search *Defender Deploy* from the Modules list, and click "Activate".
3. A new tab in the left nav bar with the OpenZeppelin icon should be displayed.


[[usage]]
== Usage

1. Export an API key from Defender, you only need _Manage Deployments_ permissions.
2. Go to Remix, open Defender Deploy plug-in.
3. In *Setup* step, set your keys and press "Authenticate".
4. In *Network* step, and select any of the supported networks.
5. In *Approval Process* step, here you have 3 options:
- Select an existing approval process from your *Deployment Environment* configured for the selected network.
- If the *Deployment Envoronment* does not exist for the selected network, then you can create one using an exiting *Approval Process* or creating one.
- Additionally, you can use the *injected provider* from Remix (a browser wallet) to deploy the contract, this will create a Defender *Deployment Environment* under the hood after deploying the contract.
6. In *Deploy* step, you should see the latest compiled contract along with the constructor inputs.
- In case you don't see it, compile the target contract again, the Defender plug-in should detect the compilation and display the contructor inputs.